import { afterEach, describe, expect, test } from 'bun:test';
import { mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import {
  type BriefState,
  loadState,
  markSeen,
  recordDeploy,
  recordExhausted,
  recordRun,
  saveState,
  slotIsComplete,
  slotIsExhausted,
  slotIsSettled,
  whichAreNew,
} from './state.ts';

const dirs: string[] = [];
function statePath(): string {
  const dir = mkdtempSync(join(tmpdir(), 'aula-state-test-'));
  dirs.push(dir);
  return join(dir, 'state.json');
}
afterEach(() => {
  for (const dir of dirs.splice(0)) rmSync(dir, { recursive: true, force: true });
});

// Local noon, so "today" is unambiguous whatever the machine's offset.
const today = new Date(2026, 7, 21, 12, 0, 0);
const earlierToday = new Date(2026, 7, 21, 6, 30, 0);
const yesterday = new Date(2026, 7, 20, 6, 30, 0);

describe('whichAreNew', () => {
  test('unseen keys are new', () => {
    const state: BriefState = { seen: {} };
    expect(whichAreNew(state, ['a', 'b'], today)).toEqual(new Set(['a', 'b']));
  });

  test('a key first seen earlier today is still new — the scheduler may build the page twice in a morning', () => {
    const state: BriefState = { seen: {} };
    markSeen(state, ['a'], earlierToday);
    expect(whichAreNew(state, ['a'], today)).toEqual(new Set(['a']));
  });

  test('a key seen on an earlier day is old', () => {
    const state: BriefState = { seen: {} };
    markSeen(state, ['a'], yesterday);
    expect(whichAreNew(state, ['a'], today)).toEqual(new Set());
  });

  test('markSeen keeps the first sighting, so a rerun cannot refresh an old item into a new one', () => {
    const state: BriefState = { seen: {} };
    markSeen(state, ['a'], yesterday);
    markSeen(state, ['a'], today);
    expect(state.seen.a).toBe(yesterday.toISOString());
  });
});

describe('the run ledger', () => {
  // The morning slot of the day the other fixtures sit in.
  const morningSlot = new Date(2026, 7, 21, 6, 0, 0);
  const eveningSlot = new Date(2026, 7, 21, 18, 0, 0);

  test('slotIsComplete needs a complete run at or after the slot began', () => {
    const state: BriefState = { seen: {} };
    expect(slotIsComplete(state, morningSlot)).toBe(false);

    recordRun(state, { day: '2026-08-21', complete: false }, earlierToday);
    expect(slotIsComplete(state, morningSlot)).toBe(false);

    recordRun(state, { day: '2026-08-21', complete: true }, earlierToday);
    expect(slotIsComplete(state, morningSlot)).toBe(true);
  });

  /**
   * The reason this is a slot and not a day. Under the previous
   * `todayIsComplete` the evening run asked whether *today* had a complete
   * brief, the morning's said yes, and the 18:00 overview was never generated
   * at all.
   */
  test("the morning's complete run does not settle the evening", () => {
    const state: BriefState = { seen: {} };
    recordRun(state, { day: '2026-08-21', complete: true }, earlierToday);
    expect(slotIsComplete(state, morningSlot)).toBe(true);
    expect(slotIsComplete(state, eveningSlot)).toBe(false);
  });

  /**
   * A brief the user generated by hand inside the slot stands in for the one
   * the scheduler owed them, which is what the day-granular version did too.
   */
  test('any complete run inside the slot counts, whoever started it', () => {
    const state: BriefState = { seen: {} };
    recordRun(state, { day: '2026-08-21', complete: true }, today);
    expect(slotIsComplete(state, morningSlot)).toBe(true);
  });

  /**
   * Without this the wake-up heartbeat turns a permanent failure into an
   * all-day one: the coordinator gives up after three hours and the heartbeat
   * hands it three more a quarter of an hour later.
   */
  test('an exhausted slot is settled without being complete', () => {
    const state: BriefState = { seen: {} };
    recordExhausted(state, morningSlot);
    expect(slotIsExhausted(state, morningSlot)).toBe(true);
    expect(slotIsComplete(state, morningSlot)).toBe(false);
    expect(slotIsSettled(state, morningSlot)).toBe(true);
    // It expires by itself: the next slot has a different start.
    expect(slotIsSettled(state, eveningSlot)).toBe(false);
  });

  /**
   * Anchored to the slot rather than kept on `lastRun`, so a later attempt
   * writing its own outcome cannot quietly hand the slot a second window.
   */
  test('a later failed run does not clear the exhaustion', () => {
    const state: BriefState = { seen: {} };
    recordExhausted(state, morningSlot);
    recordRun(state, { day: '2026-08-21', complete: false }, today);
    expect(slotIsSettled(state, morningSlot)).toBe(true);
  });

  test('exhaustion survives a round trip through the file', () => {
    const path = statePath();
    const state: BriefState = { seen: {} };
    recordExhausted(state, morningSlot);
    saveState(state, path);
    expect(slotIsExhausted(loadState(path), morningSlot)).toBe(true);
  });

  test('lastRun and lastDeploy round-trip through the file', () => {
    const path = statePath();
    const state: BriefState = { seen: {} };
    recordRun(state, { day: '2026-08-21', complete: true }, earlierToday);
    recordDeploy(
      state,
      'https://claude.ai/code/artifact/0a1b2c3d-4e5f-4a6b-8c7d-9e0f1a2b3c4d',
      earlierToday,
    );
    saveState(state, path);
    const loaded = loadState(path);
    expect(loaded.lastRun).toEqual({
      day: '2026-08-21',
      at: earlierToday.toISOString(),
      complete: true,
    });
    expect(loaded.lastDeploy).toEqual({
      url: 'https://claude.ai/code/artifact/0a1b2c3d-4e5f-4a6b-8c7d-9e0f1a2b3c4d',
      at: earlierToday.toISOString(),
      day: '2026-08-21',
    });
  });

  test('a state file with no ledger yet loads with none', () => {
    const path = statePath();
    writeFileSync(path, JSON.stringify({ seen: { a: yesterday.toISOString() } }));
    expect(loadState(path)).toEqual({ seen: { a: yesterday.toISOString() } });
  });

  test('valid JSON with the wrong shape degrades to safe state', () => {
    const path = statePath();
    writeFileSync(
      path,
      JSON.stringify({
        seen: 'not a map',
        lastRun: { day: 42, at: null, complete: 'yes' },
        lastDeploy: ['not', 'an', 'object'],
      }),
    );
    expect(loadState(path)).toEqual({ seen: {} });
  });

  test('keeps valid fields and drops malformed entries independently', () => {
    const path = statePath();
    writeFileSync(
      path,
      JSON.stringify({
        seen: { good: yesterday.toISOString(), bad: 42, invalidTimestamp: 'yesterday-ish' },
        lastRun: { day: '2026-08-21', at: earlierToday.toISOString(), complete: true },
        lastDeploy: { url: false, at: earlierToday.toISOString(), day: '2026-08-21' },
      }),
    );
    expect(loadState(path)).toEqual({
      seen: { good: yesterday.toISOString() },
      lastRun: { day: '2026-08-21', at: earlierToday.toISOString(), complete: true },
    });
  });

  test('drops ledger entries whose date-looking strings are not real dates', () => {
    const path = statePath();
    writeFileSync(
      path,
      JSON.stringify({
        seen: {},
        lastRun: { day: '2026-02-31', at: 'not-a-timestamp', complete: true },
        lastDeploy: {
          url: 'https://example.test',
          at: earlierToday.toISOString(),
          day: '2026-13-01',
        },
      }),
    );
    expect(loadState(path)).toEqual({ seen: {} });
  });
});
